/**
 * Kelvin-JS: WebAssembly-based bindings for the Kelvin cryptosystem.
 * 
 * This library expects the 'kelvin_wasm' module to be loaded.
 */

// Note: These imports would be generated by wasm-bindgen
// import init, { KelvinWasm, OrbitalConfigWasm } from './kelvin_wasm';

export class Kelvin {
  private inner: any;

  constructor(inner: any) {
    this.inner = inner;
  }

  /**
   * Encrypt/Decrypt data in-place.
   */
  async process(data: Uint8Array): Promise<void> {
    // In a real WASM implementation, this would call the WASM exports
    this.inner.process(data);
  }

  /**
   * Returns remaining safe bytes.
   */
  get remainingBytes(): bigint {
    return this.inner.remaining_safe_bytes();
  }

  /**
   * Free the underlying WASM memory.
   */
  free(): void {
    if (this.inner) {
      this.inner.free();
      this.inner = null;
    }
  }
}

export class KelvinFactory {
    /**
     * Initialize the Kelvin system from a JSON config.
     */
    static async create(configJson: string): Promise<Kelvin> {
        // Real implementation would await WASM init and then create instance
        console.log("Initializing Kelvin WASM...");
        // const config = OrbitalConfigWasm.from_json(configJson);
        // const kelvin = new KelvinWasm(config);
        // return new Kelvin(kelvin);
        throw new Error("WASM module not yet integrated in this demo.");
    }
}
