[workspace]
members = [
    "kelvin-core",
    "kelvin-kdf",
    "kelvin-stream",
    "kelvin",
    "kelvin-cli",
    "kelvin-ffi",
    "kelvin-test-server",
    "kelvin-test-client",
    "tests/constant_time_bench",
    "tests/nist_tests",
    "tests/entropy_analysis",
    "fuzz",
]

resolver = "2"
