//! # Kelvin Test Vector Client
//!
//! Verifies cross-platform determinism by comparing local encryption results
//! against golden test vectors generated by `kelvin-test-server`.
//!
//! ## Usage
//!
//! ```bash
//! # Verify against test vector files
//! kelvin-test-client --vectors ./test-vectors/
//!
//! # Verify a single test vector file
//! kelvin-test-client --file ./test-vectors/kelvin-test-standard-1.json
//! ```
//!
//! ## What it tests
//!
//! 1. **Determinism**: Same OrbitalConfig produces identical keystream
//! 2. **Round-trip**: encrypt with instance A, decrypt with instance B returns original
//! 3. **Idempotency**: encrypt with A, encrypt with B = original (XOR property)
//!
//! ## References
//!
//! - NIST SP 800-22: Statistical testing for random number generators
//! - Bernstein, D. J. (2008). "ChaCha, a variant of Salsa20."
//!   *Workshop Record of SASC 2008*.
//! - NIST FIPS PUB 202 (2015). "SHA-3 Standard: Permutation-Based Hash
//!   and Extendable-Output Functions."

use std::fs;
use std::path::PathBuf;

use kelvin::Kelvin;
use kelvin_core::{Fixed, OrbitalBody, Vec3};
use serde::{Deserialize, Serialize};

/// A single test vector for cross-platform determinism verification.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestVector {
    pub description: String,
    pub level: String,
    pub config_json: String,
    pub plaintext_hex: String,
    pub ciphertext_hex: String,
    pub keystream_hex: String,
    pub num_bodies: usize,
    pub total_steps: u64,
    pub generation_time_s: f64,
}

/// Result of verifying a single test vector.
#[derive(Debug)]
struct VerificationResult {
    #[allow(dead_code)]
    description: String,
    ciphertext_match: bool,
    round_trip_ok: bool,
    idempotent_ok: bool,
    errors: Vec<String>,
}

/// Verify a test vector against local computation.
fn verify_test_vector(vector: &TestVector) -> VerificationResult {
    let mut errors = Vec::new();

    // Parse the config
    let config: kelvin::OrbitalConfig = match serde_json::from_str(&vector.config_json) {
        Ok(c) => c,
        Err(e) => {
            return VerificationResult {
                description: vector.description.clone(),
                ciphertext_match: false,
                round_trip_ok: false,
                idempotent_ok: false,
                errors: vec![format!("Failed to parse config JSON: {}", e)],
            };
        },
    };

    // Decode plaintext
    let plaintext = match hex::decode(&vector.plaintext_hex) {
        Ok(p) => p,
        Err(e) => {
            return VerificationResult {
                description: vector.description.clone(),
                ciphertext_match: false,
                round_trip_ok: false,
                idempotent_ok: false,
                errors: vec![format!("Failed to decode plaintext hex: {}", e)],
            };
        },
    };

    // Decode expected ciphertext
    let expected_ciphertext = match hex::decode(&vector.ciphertext_hex) {
        Ok(c) => c,
        Err(e) => {
            return VerificationResult {
                description: vector.description.clone(),
                ciphertext_match: false,
                round_trip_ok: false,
                idempotent_ok: false,
                errors: vec![format!("Failed to decode ciphertext hex: {}", e)],
            };
        },
    };

    // Test 1: Determinism -- encrypt locally and compare with golden ciphertext
    let ciphertext_match = match Kelvin::new(config.clone()) {
        Ok(mut k) => {
            let mut data = plaintext.clone();
            match k.encrypt(&mut data) {
                Ok(()) => data == expected_ciphertext,
                Err(e) => {
                    errors.push(format!("Encryption failed: {}", e));
                    false
                },
            }
        },
        Err(e) => {
            errors.push(format!("Kelvin::new failed: {}", e));
            false
        },
    };

    // Test 2: Round-trip -- encrypt with instance A, decrypt with instance B
    // (Both start from same initial state, so they produce the same keystream.
    //  XOR with A, then XOR with B = original.)
    let round_trip_ok = match Kelvin::new(config.clone()) {
        Ok(mut k_enc) => {
            let mut data = plaintext.clone();
            match k_enc.encrypt(&mut data) {
                Ok(()) => match Kelvin::new(config.clone()) {
                    Ok(mut k_dec) => match k_dec.decrypt(&mut data) {
                        Ok(()) => data == plaintext,
                        Err(e) => {
                            errors.push(format!("Decryption failed: {}", e));
                            false
                        },
                    },
                    Err(e) => {
                        errors.push(format!("Kelvin::new failed (dec): {}", e));
                        false
                    },
                },
                Err(e) => {
                    errors.push(format!("Encryption failed (round-trip): {}", e));
                    false
                },
            }
        },
        Err(e) => {
            errors.push(format!("Kelvin::new failed (enc): {}", e));
            false
        },
    };

    // Test 3: Idempotency -- encrypt with A, encrypt with B = original
    // (Both start from same initial state, so they produce the same keystream.
    //  XOR with A, then XOR with B = original.)
    let idempotent_ok = match Kelvin::new(config.clone()) {
        Ok(mut k_a) => {
            let mut data = plaintext.clone();
            match k_a.encrypt(&mut data) {
                Ok(()) => match Kelvin::new(config.clone()) {
                    Ok(mut k_b) => match k_b.encrypt(&mut data) {
                        Ok(()) => data == plaintext,
                        Err(e) => {
                            errors.push(format!("Second encrypt failed: {}", e));
                            false
                        },
                    },
                    Err(e) => {
                        errors.push(format!("Kelvin::new failed (idem B): {}", e));
                        false
                    },
                },
                Err(e) => {
                    errors.push(format!("Encryption failed (idempotent): {}", e));
                    false
                },
            }
        },
        Err(e) => {
            errors.push(format!("Kelvin::new failed (idem A): {}", e));
            false
        },
    };

    VerificationResult {
        description: vector.description.clone(),
        ciphertext_match,
        round_trip_ok,
        idempotent_ok,
        errors,
    }
}

fn main() -> Result<(), String> {
    let args: Vec<String> = std::env::args().collect();

    println!("Kelvin Test Vector Client");
    println!("=========================");
    println!();

    // Collect test vector files
    let mut vector_files: Vec<PathBuf> = Vec::new();

    if args.contains(&"--file".to_string()) {
        if let Some(file) = args.iter().position(|a| a == "--file").and_then(|i| args.get(i + 1)) {
            vector_files.push(PathBuf::from(file));
        }
    } else if args.contains(&"--vectors".to_string()) {
        if let Some(dir) = args.iter().position(|a| a == "--vectors").and_then(|i| args.get(i + 1))
        {
            let dir_path = PathBuf::from(dir);
            if dir_path.is_dir() {
                for entry in fs::read_dir(&dir_path).map_err(|e| format!("FS error: {}", e))? {
                    let entry = entry.map_err(|e| format!("FS error: {}", e))?;
                    let path = entry.path();
                    if path.extension().is_some_and(|e| e == "json") {
                        vector_files.push(path);
                    }
                }
            }
        }
    }

    if vector_files.is_empty() {
        // No files specified -- run built-in self-test
        println!("No test vector files specified. Running built-in self-test...");
        println!();
        return run_self_test();
    }

    // Load and verify each test vector
    let mut all_pass = true;
    let mut total = 0;
    let mut passed = 0;

    for path in &vector_files {
        let content = fs::read_to_string(path).map_err(|e| format!("FS error: {}", e))?;
        let vector: TestVector =
            serde_json::from_str(&content).map_err(|e| format!("JSON error: {}", e))?;

        println!("Verifying: {} ({})", vector.description, path.display());
        println!(
            "  Level: {}, Bodies: {}, Steps: {}",
            vector.level, vector.num_bodies, vector.total_steps
        );

        let result = verify_test_vector(&vector);
        total += 1;

        let status = if result.ciphertext_match && result.round_trip_ok && result.idempotent_ok {
            passed += 1;
            "PASS"
        } else {
            all_pass = false;
            "FAIL"
        };

        println!(
            "  [{status}] ciphertext_match={}, round_trip={}, idempotent={}",
            result.ciphertext_match, result.round_trip_ok, result.idempotent_ok
        );

        for err in &result.errors {
            println!("    Error: {}", err);
        }
        println!();
    }

    println!("Results: {}/{} passed", passed, total);
    if all_pass {
        println!("All tests PASSED -- platform is deterministic with server.");
    } else {
        println!("Some tests FAILED -- platform is NOT deterministic with server!");
        println!("This indicates a platform-specific divergence in the simulation.");
    }

    Ok(())
}

/// Run a built-in self-test without external test vector files.
fn run_self_test() -> Result<(), String> {
    println!("Running built-in determinism self-test...");
    println!();

    // Create a simple 5-body configuration
    let bodies = vec![
        OrbitalBody::new(Fixed::ONE, Vec3::ZERO, Vec3::ZERO),
        OrbitalBody::new(
            Fixed::from_raw(1 << 54),
            Vec3::new(Fixed::ONE, Fixed::ZERO, Fixed::ZERO),
            Vec3::new(Fixed::ZERO, Fixed::from_int(6), Fixed::ZERO),
        ),
        OrbitalBody::new(
            Fixed::from_raw(1 << 54),
            Vec3::new(Fixed::from_raw(3 << 63), Fixed::ZERO, Fixed::ZERO),
            Vec3::new(Fixed::ZERO, Fixed::from_raw(4896710557980672i128), Fixed::from_raw(1 << 62)),
        ),
        OrbitalBody::new(
            Fixed::from_raw(1 << 53),
            Vec3::new(Fixed::from_int(-1), Fixed::from_int(-1), Fixed::ZERO),
            Vec3::new(Fixed::from_int(3), Fixed::from_int(-2), Fixed::ZERO),
        ),
        OrbitalBody::new(
            Fixed::from_raw(1 << 52),
            Vec3::new(Fixed::from_int(2), Fixed::from_int(-1), Fixed::from_int(1)),
            Vec3::new(Fixed::from_int(-2), Fixed::from_int(3), Fixed::ZERO),
        ),
    ];

    // Use a small step count that the Lyapunov estimator will accept.
    // The estimator typically allows ~73 safe steps for this config.
    let safe_steps: u64 = 50;
    let config = kelvin::OrbitalConfig::new(
        bodies,
        safe_steps,
        safe_steps / 10,
        Fixed::from_raw(1 << 44),
        Fixed::from_raw(1 << 44),
        kelvin_core::DEFAULT_G,
    )
    .map_err(|e| format!("Failed to create config: {}", e))?;

    let plaintext =
        b"Kelvin determinism test vector - this data should encrypt identically on all platforms.";

    // Test 1: Two independent instances with same config produce same ciphertext
    println!("Test 1: Determinism (two instances, same config)...");
    let mut k1 = Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    let mut k2 = Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;

    let mut data1 = plaintext.to_vec();
    let mut data2 = plaintext.to_vec();

    k1.encrypt(&mut data1).map_err(|e| format!("Encrypt failed: {}", e))?;
    k2.encrypt(&mut data2).map_err(|e| format!("Encrypt failed: {}", e))?;

    if data1 == data2 {
        println!("  PASS - Both instances produced identical ciphertext");
    } else {
        println!("  FAIL - Instances diverged!");
        println!("    Instance 1: {}", hex::encode(&data1));
        println!("    Instance 2: {}", hex::encode(&data2));
    }

    // Test 2: Round-trip with TWO instances (encrypt with A, decrypt with B)
    // Both start from same initial state, so they produce the same keystream.
    println!();
    println!("Test 2: Round-trip (encrypt A, decrypt B, same config)...");
    let mut k_enc =
        Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    let mut data3 = plaintext.to_vec();
    k_enc.encrypt(&mut data3).map_err(|e| format!("Encrypt failed: {}", e))?;

    let mut k_dec =
        Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    k_dec.decrypt(&mut data3).map_err(|e| format!("Decrypt failed: {}", e))?;

    if data3 == plaintext {
        println!("  PASS - Round-trip returned original plaintext");
    } else {
        println!("  FAIL - Round-trip corrupted data!");
    }

    // Test 3: Idempotency (XOR property) with TWO instances
    // encrypt with A, encrypt with B = original (XOR is its own inverse)
    println!();
    println!("Test 3: Idempotency (encrypt A, encrypt B = original)...");
    let mut k4a = Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    let mut data4 = plaintext.to_vec();
    k4a.encrypt(&mut data4).map_err(|e| format!("Encrypt failed: {}", e))?;

    let mut k4b = Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    k4b.encrypt(&mut data4).map_err(|e| format!("Encrypt failed: {}", e))?;

    if data4 == plaintext {
        println!("  PASS - Double encrypt returned original (XOR property)");
    } else {
        println!("  FAIL - Double encrypt did not return original!");
    }

    // Test 4: Empty data
    println!();
    println!("Test 4: Empty data...");
    let mut k5 = Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    let mut empty: Vec<u8> = vec![];
    match k5.encrypt(&mut empty) {
        Ok(()) => println!("  PASS - Empty data encrypt succeeded"),
        Err(e) => println!("  FAIL - Empty data encrypt failed: {}", e),
    }

    // Test 5: Large data (10KB) round-trip with TWO instances
    println!();
    println!("Test 5: Large data (10KB round-trip, two instances)...");
    let large_data = vec![0x42u8; 10_240];
    let mut k_enc2 =
        Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    let mut large_enc = large_data.clone();
    let start = std::time::Instant::now();
    k_enc2.encrypt(&mut large_enc).map_err(|e| format!("Encrypt failed: {}", e))?;

    let mut k_dec2 =
        Kelvin::new(config.clone()).map_err(|e| format!("Kelvin::new failed: {}", e))?;
    k_dec2.decrypt(&mut large_enc).map_err(|e| format!("Decrypt failed: {}", e))?;
    let elapsed = start.elapsed();

    if large_enc == large_data {
        println!("  PASS - 10KB round-trip succeeded in {:?}", elapsed);
    } else {
        println!("  FAIL - 10KB round-trip corrupted data!");
    }

    // Summary
    println!();
    println!("Self-test complete.");
    println!();
    println!("To generate golden test vectors for cross-platform verification:");
    println!("  kelvin-test-server --output ./test-vectors/");
    println!();
    println!("To verify against golden vectors on another platform:");
    println!("  kelvin-test-client --vectors ./test-vectors/");

    Ok(())
}
