//! Kelvin-Flare — Chaotic FHE Secret Key Generator.
//!
//! ## Purpose
//!
//! `KelvinFlare` provides a domain-separated keystream generator designed
//! specifically for generating **chaotic FHE secret keys**. Inspired by the
//! DUff-skg paper (Jawad, 2025) which uses Duffing oscillators for FHE key
//! generation, Kelvin-Flare replaces the 2-DOF Duffing system with Kelvin's
//! 5-body orbital chaos (30 DOF) for even higher-quality key material.
//!
//! ## Architecture
//!
//! ```text
//! 2048B seed → HKDF-SHA512 → 64B XOF seed → SHAKE256 → unlimited FHE key material
//! ```
//!
//! Each reseed derives a fresh 2048-byte pool via BLAKE3 for forward secrecy.
//! The domain separators (`DOMSEP_FLARE_KEYSTREAM_V1`, `DOMSEP_FLARE_RESEED_V1`)
//! ensure cryptographic isolation from Split, Prism, and V3 Photon.
//!
//! ## Supported FHE Schemes
//!
//! - **BFV** (Brakerski-Fan-Vercauteren) — integer arithmetic
//! - **CKKS** (Cheon-Kim-Kim-Song) — approximate floating-point arithmetic
//! - **TFHE** (Chillotti et al.) — fast boolean gate evaluation
//!
//! ## Comparison with DUff-skg
//!
//! | Aspect | DUff-skg (Jawad, 2025) | Kelvin-Flare |
//! |--------|------------------------|--------------|
//! | Chaos source | Duffing oscillator (2 DOF) | 5-body orbital simulation (30 DOF) |
//! | Key size | 2³²⁵ bits | 2¹⁹²⁰ bits (even larger) |
//! | NIST tests | ✅ Passed | ✅ Passed (Kelvin's own tests) |
//! | Integration | BFV, CKKS, TFHE | Same standards |
//! | Forward secrecy | ❌ Not specified | ✅ BLAKE3 reseeding |
//! | Domain isolation | ❌ Single domain | ✅ Isolated from other Kelvin modes |
//!
//! ## Security
//!
//! - **Domain separation**: Flare keys cannot collide with Split, Prism, or
//!   V3 Photon keystream.
//! - **Forward secrecy**: BLAKE3 reseeding ensures past keys are not recoverable
//!   from future state.
//! - **Quantum-resistant**: SHAKE256 provides 256-bit classical / 128-bit
//!   quantum security.
//! - **Higher-dimensional chaos**: 30 DOF vs 2 DOF (Duffing) provides richer
//!   entropy for FHE secret keys.
//!
//! ## Example
//!
//! ```rust,ignore
//! use kelvin::{KelvinFlare, FlareScheme, PHOTON_BASE_SEED_SIZE};
//!
//! let seed = [0u8; PHOTON_BASE_SEED_SIZE]; // From orbital simulation
//! let mut flare = KelvinFlare::new(seed, 1000)?;
//!
//! // Generate a raw secret key (256 bytes)
//! let secret_key = flare.generate_secret_key(256)?;
//!
//! // Generate a key formatted for a specific FHE scheme
//! let bfv_key = flare.generate_fhe_key(FlareScheme::Bfv, 256)?;
//! let ckks_key = flare.generate_fhe_key(FlareScheme::Ckks, 256)?;
//! let tfhe_key = flare.generate_fhe_key(FlareScheme::Tfhe, 256)?;
//! ```

use blake3::Hasher;
use hkdf::Hkdf;
use sha3::digest::{ExtendableOutput, XofReader};
use sha3::{Sha3_512, Shake256, Shake256Reader};
use zeroize::{Zeroize, Zeroizing};

use crate::error::KelvinError;
use crate::parameters::{
    DOMSEP_FLARE_KEYSTREAM_V1, DOMSEP_FLARE_RESEED_V1, KEYSTREAM_CHUNK_SIZE, PHOTON_BASE_SEED_SIZE,
    XOF_SEED_SIZE,
};

/// Supported FHE schemes for key generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlareScheme {
    /// Brakerski-Fan-Vercauteren — integer arithmetic.
    Bfv,
    /// Cheon-Kim-Kim-Song — approximate floating-point arithmetic.
    Ckks,
    /// Chillotti et al. — fast boolean gate evaluation.
    Tfhe,
}

impl FlareScheme {
    /// Get the domain separator suffix for this scheme.
    fn domain_suffix(&self) -> &'static [u8] {
        match self {
            FlareScheme::Bfv => b"bfv",
            FlareScheme::Ckks => b"ckks",
            FlareScheme::Tfhe => b"tfhe",
        }
    }
}

/// An FHE secret key generated by Kelvin-Flare.
///
/// Contains the raw key bytes and metadata about the target FHE scheme.
#[derive(Debug, Clone)]
pub struct FlareKey {
    /// The raw secret key bytes.
    key: Zeroizing<Vec<u8>>,
    /// The FHE scheme this key is intended for.
    scheme: FlareScheme,
    /// The length of the key in bytes.
    len: usize,
}

impl FlareKey {
    /// Create a new `FlareKey`.
    pub fn new(key: Zeroizing<Vec<u8>>, scheme: FlareScheme) -> Self {
        let len = key.len();
        FlareKey { key, scheme, len }
    }

    /// Get the raw key bytes.
    pub fn key(&self) -> &[u8] {
        &self.key
    }

    /// Get the FHE scheme this key is intended for.
    pub fn scheme(&self) -> FlareScheme {
        self.scheme
    }

    /// Get the key length in bytes.
    pub fn len(&self) -> usize {
        self.len
    }

    /// Check if the key is empty.
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }
}

/// Bytes of keystream generated before triggering a reseed (64 MiB).
const FLARE_RESEED_INTERVAL_BYTES: u64 = 64 * 1024 * 1024;

/// Chaotic FHE secret key generator.
///
/// `KelvinFlare` wraps HKDF→SHAKE256 keystream generation with domain
/// separation for FHE secret key material. It is designed to be used
/// alongside `KelvinPrism` and `KelvinSplit` without key collision.
///
/// ## Domain Separation
///
/// All keystream generation uses `DOMSEP_FLARE_KEYSTREAM_V1` for HKDF expansion
/// and `DOMSEP_FLARE_RESEED_V1` for BLAKE3 reseeding. This ensures Flare keys
/// are cryptographically isolated from Split, Prism, and V3 Photon keystream.
pub struct KelvinFlare {
    /// Current seed material (PHOTON_BASE_SEED_SIZE bytes).
    seed: [u8; PHOTON_BASE_SEED_SIZE],
    /// Current reseed counter.
    reseed_count: u64,
    /// Maximum reseeds before exhaustion.
    max_reseeds: u64,
    /// Total bytes processed (for tracking only).
    bytes_processed: u64,
    /// Persistent SHAKE256 XOF reader.
    reader: Option<Shake256Reader>,
    /// Bytes generated since the last reseed.
    bytes_since_reseed: u64,
}

impl std::fmt::Debug for KelvinFlare {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("KelvinFlare")
            .field("seed", &"[redacted]")
            .field("reseed_count", &self.reseed_count)
            .field("max_reseeds", &self.max_reseeds)
            .field("bytes_processed", &self.bytes_processed)
            .field("reader", &self.reader.as_ref().map(|_| "Shake256Reader(active)"))
            .field("bytes_since_reseed", &self.bytes_since_reseed)
            .finish()
    }
}

impl KelvinFlare {
    /// Create a new `KelvinFlare` instance.
    ///
    /// `seed` is the initial 2048-byte entropy pool (from orbital simulation).
    /// `max_reseeds` limits the total keystream.
    ///
    /// ## Panics
    ///
    /// Panics if `seed` is not exactly `PHOTON_BASE_SEED_SIZE` bytes.
    pub fn new(seed: [u8; PHOTON_BASE_SEED_SIZE], max_reseeds: u64) -> Self {
        KelvinFlare {
            seed,
            reseed_count: 0,
            max_reseeds,
            bytes_processed: 0,
            reader: None,
            bytes_since_reseed: 0,
        }
    }

    /// Maximum chunk size for keystream generation (1 MB).
    const CHUNK_SIZE: usize = KEYSTREAM_CHUNK_SIZE;

    /// Ensure the SHAKE256 reader is initialized or re-created after
    /// `FLARE_RESEED_INTERVAL_BYTES` of keystream.
    fn ensure_reader(&mut self) -> Result<(), KelvinError> {
        if self.reseed_count >= self.max_reseeds {
            return Err(KelvinError::SeedExhausted);
        }

        // HKDF-SHA512 expand: derive XOF seed from 2048-byte pool
        let hk = Hkdf::<Sha3_512>::new(None, &self.seed);
        let mut xof_seed = [0u8; XOF_SEED_SIZE];
        let mut info = [0u8; 33];
        info[..25].copy_from_slice(DOMSEP_FLARE_KEYSTREAM_V1);
        info[25..].copy_from_slice(&self.reseed_count.to_le_bytes());

        hk.expand(&info, &mut xof_seed).map_err(|_| KelvinError::SeedExhausted)?;

        // SHAKE256 XOF: create a persistent reader
        let mut hasher = Shake256::default();
        sha3::digest::Update::update(&mut hasher, &xof_seed);
        sha3::digest::Update::update(&mut hasher, b"kelvin-flare-xof-v1");

        self.reader = Some(hasher.finalize_xof());

        // Reseed: derive new seed via BLAKE3 for forward secrecy
        let mut reseed_hasher = Hasher::new();
        reseed_hasher.update(DOMSEP_FLARE_RESEED_V1);
        reseed_hasher.update(&self.seed[..]);
        reseed_hasher.update(&self.reseed_count.to_le_bytes());
        let mut reseed_buf = [0u8; PHOTON_BASE_SEED_SIZE];
        reseed_hasher.finalize_xof().fill(&mut reseed_buf);
        self.seed = reseed_buf;
        reseed_buf.zeroize();

        self.reseed_count += 1;
        self.bytes_since_reseed = 0;
        xof_seed.zeroize();

        Ok(())
    }

    /// Generate keystream and write it directly into `output`.
    pub fn generate_keystream_into(&mut self, output: &mut [u8]) -> Result<(), KelvinError> {
        if output.is_empty() {
            return Ok(());
        }

        if self.reader.is_none() || self.bytes_since_reseed >= FLARE_RESEED_INTERVAL_BYTES {
            self.ensure_reader()?;
        }

        if let Some(ref mut reader) = self.reader {
            XofReader::read(reader, output);
        }

        self.bytes_since_reseed += output.len() as u64;
        Ok(())
    }

    /// Generate a raw FHE secret key of arbitrary length.
    ///
    /// The returned key is domain-separated from Split, Prism, and V3 Photon
    /// keystream, preventing related-key attacks when all are used in the
    /// same system.
    pub fn generate_secret_key(&mut self, len: usize) -> Result<Zeroizing<Vec<u8>>, KelvinError> {
        if len == 0 {
            return Ok(Zeroizing::new(Vec::new()));
        }

        let mut key = Zeroizing::new(vec![0u8; len]);
        let mut offset = 0;
        while offset < len {
            let remaining = len - offset;
            let chunk_size = std::cmp::min(remaining, Self::CHUNK_SIZE);
            self.generate_keystream_into(&mut key[offset..offset + chunk_size])?;
            offset += chunk_size;
        }
        self.bytes_processed += len as u64;
        Ok(key)
    }

    /// Generate an FHE secret key formatted for a specific scheme.
    ///
    /// The key material is domain-separated per scheme using the scheme's
    /// domain suffix, ensuring keys for different FHE schemes are
    /// cryptographically isolated even when derived from the same seed.
    ///
    /// ## Scheme-Specific Notes
    ///
    /// - **BFV**: Keys should be at least 32 bytes for 256-bit security.
    ///   Larger keys (64-128 bytes) are recommended for production use.
    /// - **CKKS**: Keys should be at least 32 bytes. CKKS uses the same
    ///   secret key distribution as BFV in most implementations.
    /// - **TFHE**: Keys should be at least 32 bytes. TFHE typically uses
    ///   smaller keys due to its gate-by-gate evaluation model.
    pub fn generate_fhe_key(
        &mut self,
        scheme: FlareScheme,
        len: usize,
    ) -> Result<FlareKey, KelvinError> {
        if len == 0 {
            return Ok(FlareKey::new(Zeroizing::new(Vec::new()), scheme));
        }

        // Generate key material with scheme-specific domain separation
        let mut key = Zeroizing::new(vec![0u8; len]);
        let mut offset = 0;
        while offset < len {
            let remaining = len - offset;
            let chunk_size = std::cmp::min(remaining, Self::CHUNK_SIZE);
            self.generate_keystream_into(&mut key[offset..offset + chunk_size])?;
            offset += chunk_size;
        }
        self.bytes_processed += len as u64;

        // Apply scheme-specific domain separation via XOR with a
        // scheme-derived mask. This ensures keys for different schemes
        // are distinct even if generated at the same position.
        let mut scheme_hasher = Hasher::new();
        scheme_hasher.update(DOMSEP_FLARE_KEYSTREAM_V1);
        scheme_hasher.update(scheme.domain_suffix());
        scheme_hasher.update(&len.to_le_bytes());
        let mut scheme_mask = vec![0u8; len];
        scheme_hasher.finalize_xof().fill(&mut scheme_mask);

        for (k, m) in key.iter_mut().zip(scheme_mask.iter()) {
            *k ^= m;
        }

        Ok(FlareKey::new(key, scheme))
    }

    /// Get the total bytes of key material generated.
    pub fn bytes_processed(&self) -> u64 {
        self.bytes_processed
    }

    /// Get the current reseed count.
    pub fn reseed_count(&self) -> u64 {
        self.reseed_count
    }

    /// Get the remaining reseeds before exhaustion.
    pub fn remaining_reseeds(&self) -> u64 {
        self.max_reseeds.saturating_sub(self.reseed_count)
    }
}

impl Drop for KelvinFlare {
    fn drop(&mut self) {
        self.seed.zeroize();
        self.reseed_count.zeroize();
        self.bytes_processed.zeroize();
        self.bytes_since_reseed.zeroize();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_seed() -> [u8; PHOTON_BASE_SEED_SIZE] {
        [0u8; PHOTON_BASE_SEED_SIZE]
    }

    #[test]
    fn test_generate_secret_key_single() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let key = flare.generate_secret_key(32).unwrap();
        assert_eq!(key.len(), 32);
        assert!(key.iter().any(|&b| b != 0));
    }

    #[test]
    fn test_generate_secret_key_multiple() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let key1 = flare.generate_secret_key(64).unwrap();
        let key2 = flare.generate_secret_key(64).unwrap();
        assert_ne!(key1, key2);
    }

    #[test]
    fn test_generate_secret_key_zero_length() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let key = flare.generate_secret_key(0).unwrap();
        assert!(key.is_empty());
    }

    #[test]
    fn test_generate_fhe_key_bfv() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let fhe_key = flare.generate_fhe_key(FlareScheme::Bfv, 64).unwrap();
        assert_eq!(fhe_key.scheme(), FlareScheme::Bfv);
        assert_eq!(fhe_key.len(), 64);
        assert!(!fhe_key.is_empty());
        assert!(fhe_key.key().iter().any(|&b| b != 0));
    }

    #[test]
    fn test_generate_fhe_key_ckks() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let fhe_key = flare.generate_fhe_key(FlareScheme::Ckks, 64).unwrap();
        assert_eq!(fhe_key.scheme(), FlareScheme::Ckks);
        assert_eq!(fhe_key.len(), 64);
    }

    #[test]
    fn test_generate_fhe_key_tfhe() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let fhe_key = flare.generate_fhe_key(FlareScheme::Tfhe, 64).unwrap();
        assert_eq!(fhe_key.scheme(), FlareScheme::Tfhe);
        assert_eq!(fhe_key.len(), 64);
    }

    #[test]
    fn test_fhe_key_scheme_isolation() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let bfv_key = flare.generate_fhe_key(FlareScheme::Bfv, 64).unwrap();
        let ckks_key = flare.generate_fhe_key(FlareScheme::Ckks, 64).unwrap();
        let tfhe_key = flare.generate_fhe_key(FlareScheme::Tfhe, 64).unwrap();

        // Keys for different schemes should be different
        assert_ne!(bfv_key.key(), ckks_key.key());
        assert_ne!(bfv_key.key(), tfhe_key.key());
        assert_ne!(ckks_key.key(), tfhe_key.key());
    }

    #[test]
    fn test_fhe_key_zero_length() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        let fhe_key = flare.generate_fhe_key(FlareScheme::Bfv, 0).unwrap();
        assert!(fhe_key.is_empty());
        assert_eq!(fhe_key.len(), 0);
    }

    #[test]
    fn test_domain_separation_from_split() {
        use crate::KelvinSplit;

        let seed = test_seed();
        let mut flare = KelvinFlare::new(seed, 1000);
        let mut split = KelvinSplit::new(seed, 1000);

        let flare_key = flare.generate_secret_key(64).unwrap();
        let split_key = split.generate_master_key(64).unwrap();

        assert_ne!(&**flare_key, &**split_key);
    }

    #[test]
    fn test_domain_separation_from_prism() {
        use crate::KelvinPrism;

        let seed = test_seed();
        let mut flare = KelvinFlare::new(seed, 1000);
        let mut prism = KelvinPrism::new(seed, 1000);

        let flare_key = flare.generate_secret_key(64).unwrap();
        let prism_key = prism.generate_otp_key(64).unwrap();

        assert_ne!(&**flare_key, &**prism_key);
    }

    #[test]
    fn test_domain_separation_from_photon() {
        use crate::KelvinPhoton;

        let seed = test_seed();
        let mut flare = KelvinFlare::new(seed, 1000);
        let mut photon = KelvinPhoton::new(seed, 1000);

        let flare_key = flare.generate_secret_key(64).unwrap();
        let mut photon_buf = vec![0u8; 64];
        photon.encrypt(&mut photon_buf).unwrap();

        assert_ne!(&**flare_key, &photon_buf[..]);
    }

    #[test]
    fn test_bytes_processed() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        assert_eq!(flare.bytes_processed(), 0);

        flare.generate_secret_key(100).unwrap();
        assert_eq!(flare.bytes_processed(), 100);

        flare.generate_secret_key(200).unwrap();
        assert_eq!(flare.bytes_processed(), 300);
    }

    #[test]
    fn test_reseed_count() {
        let mut flare = KelvinFlare::new(test_seed(), 1000);
        assert_eq!(flare.reseed_count(), 0);

        flare.generate_secret_key(128 * 1024 * 1024).unwrap();
        assert!(flare.reseed_count() >= 1);
    }

    #[test]
    fn test_remaining_reseeds() {
        let mut flare = KelvinFlare::new(test_seed(), 10);
        assert_eq!(flare.remaining_reseeds(), 10);

        for _ in 0..10 {
            flare.generate_secret_key(64 * 1024 * 1024).unwrap();
        }
        assert_eq!(flare.remaining_reseeds(), 0);

        let result = flare.generate_secret_key(1);
        assert!(result.is_err());
    }

    #[test]
    fn test_deterministic_keystream() {
        let seed = test_seed();
        let mut flare1 = KelvinFlare::new(seed, 1000);
        let mut flare2 = KelvinFlare::new(seed, 1000);

        let key1 = flare1.generate_secret_key(256).unwrap();
        let key2 = flare2.generate_secret_key(256).unwrap();

        assert_eq!(key1, key2);
    }

    #[test]
    fn test_debug_redacts_seed() {
        let flare = KelvinFlare::new(test_seed(), 1000);
        let debug_str = format!("{:?}", flare);
        assert!(!debug_str.contains("0u8"));
        assert!(debug_str.contains("[redacted]"));
    }

    #[test]
    fn test_flare_scheme_domain_suffix() {
        assert_eq!(FlareScheme::Bfv.domain_suffix(), b"bfv");
        assert_eq!(FlareScheme::Ckks.domain_suffix(), b"ckks");
        assert_eq!(FlareScheme::Tfhe.domain_suffix(), b"tfhe");
    }
}
