[package]
name = "kelvin"
version = "0.1.0"
edition = "2021"
description = "Top-level orchestrator for Kelvin cryptosystem"
license = "CC-BY-NC-SA-4.0"

[lib]
name = "kelvin"
path = "src/lib.rs"

[dependencies]
kelvin-core = { path = "../kelvin-core" }
kelvin-kdf = { path = "../kelvin-kdf" }
kelvin-stream = { path = "../kelvin-stream" }
aead = { version = "0.5", features = ["stream"] }
blake3 = "1.5"
hkdf = "0.12"
sha3 = { version = "0.10", default-features = false }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
zeroize = { version = "1.6", features = ["zeroize_derive"] }
subtle = "2"
sha3-kmac = "0.3.0"
chacha20poly1305 = "0.10"
chacha20 = "0.9"


[[test]]
name = "authenticated"
path = "../tests/kelvin_tests/authenticated.rs"

[[test]]
name = "full_pipeline"
path = "../tests/kelvin_tests/full_pipeline.rs"

[[test]]
name = "photon"
path = "../tests/kelvin_tests/photon.rs"

[[test]]
name = "prism"
path = "../tests/kelvin_tests/prism.rs"

[[test]]
name = "quantum"
path = "../tests/kelvin_tests/quantum.rs"

[[test]]
name = "streaming_api"
path = "../tests/kelvin_tests/streaming_api.rs"

[[test]]
name = "v1_round_trip"
path = "../tests/kelvin_tests/v1_round_trip.rs"

[[test]]
name = "split"
path = "../tests/kelvin_tests/split.rs"

[[test]]
name = "flare"
path = "../tests/kelvin_tests/flare.rs"

[features]
default = []
serde = ["dep:serde", "dep:serde_json", "kelvin-kdf/serde"]
aes-ni = ["kelvin-stream/aes-ni"]
